# TD 1 | Introduction à Python pour l'analyse de données

---

Objectifs du TD :

* découvrir Python
* se familiariser avec le langage et le notebook Jupyter
* découvrir et maîtriser les bases des librairies de calcul numérique et d'analyse de données numpy et pandas

---

##  Installation de Python et Jupyter

### Windows

#### Installation Python

Vérifiez si vous avez déjà une version de python installée en ouvrant l'invite de commande et en exécutant l'une des deux commandes python suivantes : 
> python --version   

> python3 --version 

Si ce n'est pas le cas, vous pouvez procéder à l'installation comme suit :
 
1. Allez sur le site web : https://www.python.org/downloads/windows/
2. Cliquez sur "Latest Python 3 Release - Python 3.10.7".
3. Si votre ordinateur utilise une version 64 bits de Windows, téléchargez le Windows installer (64-bit). Sinon, téléchargez Windows installer (32-bit).
4. Après avoir téléchargé le Windows installer, vous devez l'exécuter (double-cliquez dessus) et suivre les instructions qui s'y trouvent.

NB : Au début de l'installation, assurez-vous de cocher la case "Add Python 3.10 to PATH" ou "Add Python to your environment variables" avant de cliquer sur "Install Now".


#### Installation Jupyter

Ouvrir l'invite de commande et exécuter la commande suivante en remplaçant Pseudo_de_votre_user par le nom de l'utilisateur de votre session : 
> cd "C:\Users\Pseudo_de_votre_user\AppData\Local\Programs\Python\Python310\Scripts"

Ensuite, executer la commande suivante :
> pip install jupyterlab

Une fois l'installation terminée avec succès, vous pouvez lancer JupyterLab avec la commande suivante : 
> jupyter-lab


### Linux & Mac OS

#### Installation Python

Normalement, Python est préinstallé sur la quasi-totalité des distributions. Vous n'avez pas besoin de le réinstaller, mais vous pouvez mettre à jour la version si vous le souhaitez.

Vérifiez la version Python installée en exécutant l'une des deux commandes python suivantes sur votre terminal : 
> python --version   

> python3 --version 

#### Installation Jupyter

Vérifier que la commande pip3 est installée. Sinon, l'installer (exemple pour Debian/Ubuntu/Linux Mint, à adapter selon votre distribution) :

> sudo apt install python3-pip

Ensuite, installer JupyterLab en executant la commande suivante:
> pip3 install -U jupyterlab

Enfin, placez-vous dans votre dossier de travail et lancez un notebook :

> jupyter-lab

## Syntaxe et Concepts de base

In [28]:
a = 33
b = 9
c = 2.0

In [29]:
a+b

42

In [30]:
print(a+b)

42


In [31]:
type(a)

int

In [32]:
type(c)

float

In [33]:
a = 'hello'
type(a)

str

In [34]:
# Affiche les entiers pairs de 1 à 10
for i in range(1, 11):
    if i % 2 == 0:
        print(i)

2
4
6
8
10


### List

In [35]:
l = [1,2,3,4,4]

#### len, max, min

In [36]:
print('longueur de la liste =', len(l))
print("Valeur max de l =", max(l))
print("Valeur min de l =", min(l))

longueur de la liste = 5
Valeur max de l = 4
Valeur min de l = 1


#### Ajout d'un élément d'une liste

In [37]:
l.append(6)
l

[1, 2, 3, 4, 4, 6]

In [38]:
l = l+[7]
l

[1, 2, 3, 4, 4, 6, 7]

In [39]:
l+=[7]
l

[1, 2, 3, 4, 4, 6, 7, 7]

#### Modifier un élément

In [40]:
l[0] = 29
l

[29, 2, 3, 4, 4, 6, 7, 7]

In [41]:
l.insert(1,9)
l

[29, 9, 2, 3, 4, 4, 6, 7, 7]

#### Suppression des éléments d'une liste

In [42]:
l.remove(7)
l

[29, 9, 2, 3, 4, 4, 6, 7]

In [43]:
l.pop(2)
l

[29, 9, 3, 4, 4, 6, 7]

#### Trier une liste

In [44]:
l.sort(reverse=True)
print(l)

[29, 9, 7, 6, 4, 4, 3]


In [45]:
l_sorted = sorted(l)
print('Sorted list:', l_sorted)

Sorted list: [3, 4, 4, 6, 7, 9, 29]


#### Liste non homogène

In [46]:
l = [1, 'un', 2]
l.append('deux')
l += [3, 'trois']
print(type(l))
l

<class 'list'>


[1, 'un', 2, 'deux', 3, 'trois']

In [47]:
a = l[3], l[-1]
print(type(a))
a

<class 'tuple'>


('deux', 'trois')

In [48]:
a[0]

'deux'

In [49]:
[2**p for p in range(10)] # "Compréhension de liste"

[1, 2, 4, 8, 16, 32, 64, 128, 256, 512]

In [50]:
# Liste des entiers pairs de 1 à 10
l = [i for i in range(1, 11) if i % 2 == 0]
print(l)

[2, 4, 6, 8, 10]


### Tuple

In [51]:
p = tuple(range(1,5))
print("p=", p)
print("p[0] = ", p[0])

p= (1, 2, 3, 4)
p[0] =  1


In [52]:
p = ([1,2],5)

print(p)

p[0][0] = 8

print(p)

([1, 2], 5)
([8, 2], 5)


In [53]:
# Les éléments du tuple sont fixes
p[0] = 6

TypeError: 'tuple' object does not support item assignment

In [54]:
p1 = (1,2)
p2 = (2,1)

print(p1 == p2)

False


### Set

In [55]:
s = set((1,2,'l'))
print(s)

s = {4,5,9,9,9,9}
print(s)

{1, 2, 'l'}
{9, 4, 5}


In [56]:
#Ajout d'un élément au set
s.add(6)
print(s)

{9, 4, 5, 6}


In [57]:
#Suppression d'un élément du set
s.discard(5)
print(s)

{9, 4, 6}


In [58]:
s.clear()
print(s)

set()


In [32]:
A = {1,2,3,4,5}
B = {2,4,6,7}
C = {1,2,3}

In [33]:
#Intersection
print("Intersection de A et B =", A&B)

#Union
print("Union entre A et B =", A|B)

#Exclusion
print("Exclusion de B de A =", A-B)

#Différence symétrique
print("Diff sym. A et B =", A^B)

Intersection de A et B = {2, 4}
Union entre A et B = {1, 2, 3, 4, 5, 6, 7}
Exclusion de B de A = {1, 3, 5}
Diff sym. A et B = {1, 3, 5, 6, 7}


In [34]:
print("B est inclus strict dans A") if A>B else print(False)
print("C est inclus dans A") if A>=C else print(False)

False
C est inclus dans A


### Dictionary

In [35]:
# 1ère façon de créer un dictionnaire
dic = {"key1": "value1", "answer": 42}
# 2ème façon de créer un dictionnaire
dic2 = dict(key1="value1", answer=42)
# 3ème façon de créer un dictionnaire
dic3 = dict([("key1","value1"), ("answer",42)])
print(dic)
print(dic2)
print(dic3)

dic["answer"]

{'key1': 'value1', 'answer': 42}
{'key1': 'value1', 'answer': 42}
{'key1': 'value1', 'answer': 42}


42

In [36]:
dic['new'] = [1,2,3]

In [37]:
dic.keys()

dict_keys(['key1', 'answer', 'new'])

In [38]:
dic.items()

dict_items([('key1', 'value1'), ('answer', 42), ('new', [1, 2, 3])])

In [39]:
dic.values()

dict_values(['value1', 42, [1, 2, 3]])

In [40]:
a,b,c = dic.items()
print(a)

('key1', 'value1')


## Programmation Orientée Objet

In [41]:
"""
Exemple de classe en Python
"""
class Moteur:
    
    # Constructeur
    def __init__(self, esn, panne=False):
        self.esn = esn
        self.panne = panne
    
    # Méthodes
    def dire_bonjour(self):
        print('Bonjour, mon numéro de série est ' + self.esn)
    
    def fonctionne(self):
        return not self.panne 
    

In [42]:
mot1 = Moteur('420912')
mot2 = Moteur(panne=True, esn='420913')

mot1.dire_bonjour()
print(mot1.fonctionne())

mot1.panne = True
print(mot1.fonctionne())

print('\n')
mot2.dire_bonjour()
print(mot2.fonctionne())

Bonjour, mon numéro de série est 420912
True
False


Bonjour, mon numéro de série est 420913
False


### Méthode récurcive vs Méthode itérative

In [43]:
# Méthode récursive
def fact1(n):
    if n == 0:
        return 1
    else:
        return n*fact1(n-1)

# Méthode itérative
def fact2(n):
    s=1
    for i in range(1,n+1):
        s*=i
    return s

print(fact1(5))
print(fact2(5))

120
120


In [44]:
"""
App.1 : Ecrire une fonction qui retourne le plus grand commun diviseur (pgcd) entre deux nombres a et b.
"""

'\nApp.1 : Ecrire une fonction qui retourne le plus grand commun diviseur (pgcd) entre deux nombres a et b.\n'

In [46]:
"""
App.1 : Correction
"""

#Méthode itérative
def pgcd1(a,b):
    while (a%b) != 0:
        s = a%b
        a = b
        b = s
    return b


#Méthode récurcive
def pgcd2(a,b):
    if a==b : return a 
    if a<b : a,b = b,a
    return pgcd2(a-b,b)

a = 230
b = 25

print("pgcd1(a,b) = ", pgcd1(a,b))
print("pgcd2(a,b) = ", pgcd2(a,b))

pgcd1(a,b) =  5
pgcd2(a,b) =  5


## Libraries

> pip install numpy pandas

> pip3 install -U numpy pandas

### Math

In [47]:
import math

In [48]:
x = 4

print("sqrt(x) =", math.sqrt(x))
print("cos(x) =", math.cos(x))
print("sin(x) =", math.sin(x))
print("factorial(x) =", math.factorial(x))

sqrt(x) = 2.0
cos(x) = -0.6536436208636119
sin(x) = -0.7568024953079283
factorial(x) = 24


### Numpy

In [49]:
import numpy as np

In [50]:
# Création d'un array à partir d'une liste
v = np.array([1.0, 2.0, 3.0])
# Création d'un array de taille (n,m) initialisé à 0
z = np.zeros((3,4))
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
# Taille d'un array
print(z.shape)
print(v.shape)

(3, 4)
(3,)


In [52]:
# Opérations courantes
A = np.ones((3,3)) + np.eye(3)
print('A = ', A)
print('Av = ', np.dot(A,v))
print('3*A = ', 3*A)
print('A*v = ', A*v)
print('A + 1 = ', A+1)
print('A + v = ', A+v)
print('A^2 = ', np.square(A))

A =  [[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]
Av =  [7. 8. 9.]
3*A =  [[6. 3. 3.]
 [3. 6. 3.]
 [3. 3. 6.]]
A*v =  [[2. 2. 3.]
 [1. 4. 3.]
 [1. 2. 6.]]
A + 1 =  [[3. 2. 2.]
 [2. 3. 2.]
 [2. 2. 3.]]
A + v =  [[3. 3. 4.]
 [2. 4. 4.]
 [2. 3. 5.]]
A^2 =  [[4. 1. 1.]
 [1. 4. 1.]
 [1. 1. 4.]]


In [53]:
B = np.array([5, 2, 9, 1])

print(np.sort(B))

[1 2 5 9]


#### Compatif de performance : produit matriciel


In [54]:
import random

In [55]:
# Création d'une matrice aléatoire sous forme de liste de listes
taille = 2
A = [[random.random() for _ in range(taille)] for _ in range(taille)]

In [56]:
print(A)

[[0.9259818241450817, 0.5873046542719569], [0.09691741212514338, 0.5629787140725184]]


In [57]:
"""
EXERCICE - Afficher un tuple contenant les dimensions de la matrice A
"""
print(np.shape(A))

(2, 2)


$$ (AB)_{ij} = \sum_k A_{ik} B_{kj} $$

In [58]:
"""
EXERCICE - Implémenter le produit matriciel de 2 matrices sous forme de listes de listes python
"""
def produit(A, B):
    result = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]

    return result

B = [[5, 6], [7, 8]]
resultat = produit(A, B)

for ligne in resultat:
    print(ligne)


[8.741041700629106, 10.254328179046144]
[4.425438059133346, 5.085334185331008]


In [59]:
# Vérification
assert(produit([[1, 2], [3, 4]], [[1, 2], [3, 4]]) == [[7, 10], [15, 22]])

In [60]:
produit(A, A)

[[0.9143623858681431, 0.8744734541224745],
 [0.14430620212051046, 0.3738650797198365]]

In [61]:
# Sortons le chronomètre
%timeit produit(A, A)

851 ns ± 1.87 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [62]:
# Et maintenant, avec numpy !
import numpy as np

In [63]:
A2 = np.array(A)
print(A2)

[[0.92598182 0.58730465]
 [0.09691741 0.56297871]]


In [64]:
%timeit np.dot(A, A)

1.16 μs ± 7.38 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


EXERCICE - Remplissez le tableau suivant avec les durées d'exécution constatées :

(Conseil : pour la taille 3000, essayez UNIQUEMENT avec numpy)

Taille | Python | numpy
-------|--------|-------
30     | XXX    | XXX
300    | XXX    | XXX
3000   | XXX    | XXX 

###  Pandas

In [59]:
import pandas as pd

In [60]:
df_exemple = pd.DataFrame({"ESN": ["E420912", "E420913", "E420914"], "panne": [False, False, True]})
df_exemple

ESN  panne
0  E420912  False
1  E420913  False
2  E420914   True

#### Lecture et prétraitement de données


In [61]:
!git clone https://github.com/MadaneA/MACS3_Stats_TDs.git

fatal: destination path 'MACS3_Stats_TDs' already exists and is not an empty directory.


In [62]:
import os
os.chdir('MACS3_Stats_TDs')

In [63]:
 os.getcwd()

'/Users/yacinebenami/Desktop/MACS3/Analyse_de_donnees/MACS3_Stats_TDs'

In [64]:
# Chargement d'un fichier CSV ou Excel
df = pd.read_csv("./data/Vol010.csv")
# Affichage des 5 premières lignes
df.head()

t EGT_SEL FLIGHT_MOD FMV_SEL HPTC_SEL LPTC_SEL  \
0                  datenum   deg_C          _       _        %        %   
1  15/09/2011 14:25:58.125     NaN        NaN     NaN      NaN      NaN   
2  15/09/2011 14:25:58.375     NaN        NaN     NaN      NaN      NaN   
3  15/09/2011 14:25:58.625     NaN        NaN     NaN      NaN      NaN   
4  15/09/2011 14:25:58.875     NaN        NaN     NaN      NaN      NaN   

  N1_SEL N2_ACTSEL OIL_P OIL_TEMP  ... T25_SEL T3_SEL VBV_SEL VIB_CN1 VIB_CN2  \
0      %     %_RPM   psi        _  ...       _      _     DEG       _       _   
1    NaN         0   NaN      NaN  ...     NaN    NaN     NaN     NaN     NaN   
2    NaN         0   NaN      NaN  ...     NaN    NaN     NaN     NaN     NaN   
3    NaN         0   NaN      NaN  ...     NaN    NaN     NaN     NaN     NaN   
4    NaN         0   NaN      NaN  ...     NaN    NaN     NaN     NaN     NaN   

  VIB_TN1 VIB_TN2 VSV_SEL  WFM_SEL    XM  
0       _       _     DEG     lb/h  mach  
1     NaN     NaN     NaN      NaN   NaN  
2     NaN     NaN     NaN      NaN   NaN  
3     NaN     NaN     NaN      NaN   NaN  
4     NaN     NaN     NaN  7679.98  0.15  

[5 rows x 26 columns]

In [65]:
"""
EXERCICE - Dimensions d'un DataFrame
Affichez le nombre de colonnes et de ligne du DataFrame (indice : beaucoup de méthodes sont communes entre numpy et pandas)
"""
nombre_lignes, nombre_colonnes = df.shape

print('Nombre de colonnes :', nombre_colonnes )
print('Nombre de lignes :', nombre_lignes )

Nombre de colonnes : 26
Nombre de lignes : 22945


In [66]:
df.size, len(df)

(596570, 22945)

In [67]:
df.columns

Index(['t', 'EGT_SEL', 'FLIGHT_MOD', 'FMV_SEL', 'HPTC_SEL', 'LPTC_SEL',
       'N1_SEL', 'N2_ACTSEL', 'OIL_P', 'OIL_TEMP', 'PS3_SEL', 'PT2_SEL',
       'P0_SEL', 'TAT', 'TBV_SEL', 'TRA_SEL', 'T25_SEL', 'T3_SEL', 'VBV_SEL',
       'VIB_CN1', 'VIB_CN2', 'VIB_TN1', 'VIB_TN2', 'VSV_SEL', 'WFM_SEL', 'XM'],
      dtype='object')

Les colonnes des DF sont typées, à la manière d'une base de données relationnelle, contrairement aux variables python classiques. Les types des colonnes sont accessibles via df.dtypes. Les principaux types sont les numériques (int32, int64, float etc.

In [68]:
df.loc[10:15, ['EGT_SEL', 'FLIGHT_MOD']]

EGT_SEL FLIGHT_MOD
10    0.00234327        NaN
11  1.08032e-007        NaN
12  3.12514e-012        NaN
13             0        NaN
14       72.0006        NaN
15       215.996        NaN

In [69]:
"""
EXERCICE - Extraction et suppression des unités
On remarque que la 1ère ligne ne contient pas de données mais les unités de chaque colonne.
Pour la suite des traitements, il faut supprimer cette ligne. On souhaite toutefois garder l'information des unités de chaque colonne.
1. Récupérez les unités et stockez les dans une structure adaptée.
2. Supprimez cette ligne du DataFrame en utilisant la méthode "drop"
"""

unites = df.iloc[0].to_dict()


df = df.drop(0).reset_index(drop=True)


print("Unité des colonnes :", unites)
print("DataFrame sans la première ligne :",df)



Unité des colonnes : {'t': 'datenum', 'EGT_SEL': 'deg_C', 'FLIGHT_MOD': '_', 'FMV_SEL': '_', 'HPTC_SEL': '%', 'LPTC_SEL': '%', 'N1_SEL': '%', 'N2_ACTSEL': '%_RPM', 'OIL_P': 'psi', 'OIL_TEMP': '_', 'PS3_SEL': 'psi', 'PT2_SEL': 'mb', 'P0_SEL': 'psi', 'TAT': 'deg_C', 'TBV_SEL': '%', 'TRA_SEL': 'DEG', 'T25_SEL': '_', 'T3_SEL': '_', 'VBV_SEL': 'DEG', 'VIB_CN1': '_', 'VIB_CN2': '_', 'VIB_TN1': '_', 'VIB_TN2': '_', 'VSV_SEL': 'DEG', 'WFM_SEL': 'lb/h', 'XM': 'mach'}
DataFrame sans la première ligne :                              t EGT_SEL FLIGHT_MOD FMV_SEL HPTC_SEL LPTC_SEL  \
0      15/09/2011 14:25:58.125     NaN        NaN     NaN      NaN      NaN   
1      15/09/2011 14:25:58.375     NaN        NaN     NaN      NaN      NaN   
2      15/09/2011 14:25:58.625     NaN        NaN     NaN      NaN      NaN   
3      15/09/2011 14:25:58.875     NaN        NaN     NaN      NaN      NaN   
4      15/09/2011 14:25:59.125     NaN        NaN     NaN      NaN      NaN   
...                        .

In [70]:
print(unites)
df.head()

{'t': 'datenum', 'EGT_SEL': 'deg_C', 'FLIGHT_MOD': '_', 'FMV_SEL': '_', 'HPTC_SEL': '%', 'LPTC_SEL': '%', 'N1_SEL': '%', 'N2_ACTSEL': '%_RPM', 'OIL_P': 'psi', 'OIL_TEMP': '_', 'PS3_SEL': 'psi', 'PT2_SEL': 'mb', 'P0_SEL': 'psi', 'TAT': 'deg_C', 'TBV_SEL': '%', 'TRA_SEL': 'DEG', 'T25_SEL': '_', 'T3_SEL': '_', 'VBV_SEL': 'DEG', 'VIB_CN1': '_', 'VIB_CN2': '_', 'VIB_TN1': '_', 'VIB_TN2': '_', 'VSV_SEL': 'DEG', 'WFM_SEL': 'lb/h', 'XM': 'mach'}


t EGT_SEL FLIGHT_MOD FMV_SEL HPTC_SEL LPTC_SEL  \
0  15/09/2011 14:25:58.125     NaN        NaN     NaN      NaN      NaN   
1  15/09/2011 14:25:58.375     NaN        NaN     NaN      NaN      NaN   
2  15/09/2011 14:25:58.625     NaN        NaN     NaN      NaN      NaN   
3  15/09/2011 14:25:58.875     NaN        NaN     NaN      NaN      NaN   
4  15/09/2011 14:25:59.125     NaN        NaN     NaN      NaN      NaN   

  N1_SEL N2_ACTSEL    OIL_P OIL_TEMP  ... T25_SEL T3_SEL VBV_SEL VIB_CN1  \
0    NaN         0      NaN      NaN  ...     NaN    NaN     NaN     NaN   
1    NaN         0      NaN      NaN  ...     NaN    NaN     NaN     NaN   
2    NaN         0      NaN      NaN  ...     NaN    NaN     NaN     NaN   
3    NaN         0      NaN      NaN  ...     NaN    NaN     NaN     NaN   
4      0         0  647.998      NaN  ...     NaN    NaN       0       0   

  VIB_CN2 VIB_TN1 VIB_TN2 VSV_SEL  WFM_SEL    XM  
0     NaN     NaN     NaN     NaN      NaN   NaN  
1     NaN     NaN     NaN     NaN      NaN   NaN  
2     NaN     NaN     NaN     NaN      NaN   NaN  
3     NaN     NaN     NaN     NaN  7679.98  0.15  
4       0       0       0       0  4607.86  0.15  

[5 rows x 26 columns]

On remarque que toutes les colonnes ont été reconnues comme de type object, c'est-à-dire des chaînes de caractères, alors que ce sont des valeurs numériques. Cela est dû à la première ligne contenant les unités. Il faut donc convertir les colonnes en numérique. La colonne 't', quant à elle, doit être convertie en type datetime.

In [71]:
df['t'] = pd.to_datetime(df['t'])
df[df.columns[1:]] = df[df.columns[1:]].apply(pd.to_numeric)

/var/folders/sz/74ncbmz13mg67zx7q7r3_4f00000gn/T/ipykernel_1170/2306591669.py:1: UserWarning: Parsing dates in %d/%m/%Y %H:%M:%S.%f format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['t'] = pd.to_datetime(df['t'])


In [72]:
df.dtypes

t             datetime64[ns]
EGT_SEL              float64
FLIGHT_MOD           float64
FMV_SEL              float64
HPTC_SEL             float64
LPTC_SEL             float64
N1_SEL               float64
N2_ACTSEL            float64
OIL_P                float64
OIL_TEMP             float64
PS3_SEL              float64
PT2_SEL              float64
P0_SEL               float64
TAT                  float64
TBV_SEL              float64
TRA_SEL              float64
T25_SEL              float64
T3_SEL               float64
VBV_SEL              float64
VIB_CN1              float64
VIB_CN2              float64
VIB_TN1              float64
VIB_TN2              float64
VSV_SEL              float64
WFM_SEL              float64
XM                   float64
dtype: object

In [73]:
"""
Exercice - Index temporel
Comme nos données sont une série temporelle multivariée, on souhaite utiliser un index temporel.
1. Créez une copie de df, appelée df2, à l'aide de la méthode du même nom.
2. Affectez la colonne du temps ('t') en tant qu'indice du DataFrame.
3. Supprimez la colonne 't' du DF résultant.
"""
df2 = df.copy()
df2 = df2.set_index('t')
print("DataFrame original :")
print(df)
print("\nDataFrame avec 't' comme index :")
print(df2)



DataFrame original :
                            t  EGT_SEL  FLIGHT_MOD  FMV_SEL  HPTC_SEL  \
0     2011-09-15 14:25:58.125      NaN         NaN      NaN       NaN   
1     2011-09-15 14:25:58.375      NaN         NaN      NaN       NaN   
2     2011-09-15 14:25:58.625      NaN         NaN      NaN       NaN   
3     2011-09-15 14:25:58.875      NaN         NaN      NaN       NaN   
4     2011-09-15 14:25:59.125      NaN         NaN      NaN       NaN   
...                       ...      ...         ...      ...       ...   
22939 2011-09-15 16:01:32.875      NaN         NaN      NaN       NaN   
22940 2011-09-15 16:01:33.125      NaN         NaN      NaN       NaN   
22941 2011-09-15 16:01:33.375      NaN         NaN      NaN       NaN   
22942 2011-09-15 16:01:33.625      NaN         NaN      NaN       NaN   
22943 2011-09-15 16:01:33.875      NaN         NaN      NaN       NaN   

       LPTC_SEL  N1_SEL  N2_ACTSEL    OIL_P  OIL_TEMP  ...  T25_SEL  T3_SEL  \
0           NaN     NaN

On constate que pandas a automatiquement reconnu un DatetimeIndex, adapté pour des manipulations de séries temporelles (moyennes glissantes, etc) !

### Valeurs manquantes

**NaN = Not a Number**

Les valeurs NaN doivent être éliminées ou imputées (i.e. remplacées par une certaine valeur) avant la suite des traitements. Ce choix dépend du cas d'usage. Dans un premier temps, nous allons apprendre à :

* trouver les données manquantes (méthode `isna`)
* éliminer les données manquantes d'un DataFrame (méthode `dropna`)
* les remplacer par une constante (méthode (`fillna`)

In [74]:
"""
EXERCICE - La méthode isna
1. Testez la méthode isna sur le DataFrame df2, puis sur une colonne ou une ligne. Que renvoie-t-elle ?
2. En appliquant les méthodes any(axis=...), mean() et max()/idxmax() sur les résultats de isna(), répondez aux questions suivantes :
    2.1 Quelles colonnes contiennent des valeurs manquantes, lesquelles n'en contiennent pas ?
    2.2 Quel est le pourcentage de valeurs manquantes dans le DF (a) par colonne (b) globalement ? Quelle variable contient le plus de NaN ?
    2.3 Quel est le pourcentage d'indices du DF pour lesquels toutes les variables sont présentes ?
"""

# 1. Tester la méthode isna() sur df2
print("isna() sur le DataFrame :")
print(df2.isna())

# Tester sur une colonne
print("\nisna() sur la colonne 'EGT_SEL' :")
print(df2['EGT_SEL'].isna())

# Tester sur une ligne
print("\nisna() sur la première ligne :")
print(df2.iloc[0].isna())

print('Question 2.1')
colonnes_nan = df2.isna().any()
print("\nColonnes avec des valeurs manquantes :")
print(colonnes_nan)
print('Question 2.2')
pourcentage_nan_colonnes = df2.isna().mean() * 100
print("\nPourcentage de valeurs manquantes par colonne :")
print(pourcentage_nan_colonnes)
pourcentage_nan_total = df2.isna().mean().mean() * 100
print("\nPourcentage global de valeurs manquantes :")
print(pourcentage_nan_total)
max_nan_colonne = df2.isna().mean().idxmax()
print("\nLa colonne avec le plus de NaN est :", max_nan_colonne)
print('Question 2.3')
lignes_completes = (~df2.isna().any(axis=1)).mean() * 100
print("\nPourcentage de lignes avec toutes les valeurs présentes :")
print(lignes_completes)

isna() sur le DataFrame :
                         EGT_SEL  FLIGHT_MOD  FMV_SEL  HPTC_SEL  LPTC_SEL  \
t                                                                           
2011-09-15 14:25:58.125     True        True     True      True      True   
2011-09-15 14:25:58.375     True        True     True      True      True   
2011-09-15 14:25:58.625     True        True     True      True      True   
2011-09-15 14:25:58.875     True        True     True      True      True   
2011-09-15 14:25:59.125     True        True     True      True      True   
...                          ...         ...      ...       ...       ...   
2011-09-15 16:01:32.875     True        True     True      True      True   
2011-09-15 16:01:33.125     True        True     True      True      True   
2011-09-15 16:01:33.375     True        True     True      True      True   
2011-09-15 16:01:33.625     True        True     True      True      True   
2011-09-15 16:01:33.875     True        True     T

In [78]:
"""
EXERCICE - La méthode dropna
La méthode dropna permet d'éliminer les valeurs manquantes (NaN). Lisez d'abord sa documentation.
1. À quoi correspondent les arguments "axis" et "how" ?
2. Éliminez toutes les lignes contenant uniquement des valeurs manquantes.
3. Éliminez toutes les lignes contenant au moins une valeur manquante. Combien y a-t-il de lignes de différence ?
4. Éliminez toutes les colonnes contenant au moins une valeur manquante.
"""



'\nEXERCICE - La méthode dropna\nLa méthode dropna permet d\'éliminer les valeurs manquantes (NaN). Lisez d\'abord sa documentation.\n1. À quoi correspondent les arguments "axis" et "how" ?\n2. Éliminez toutes les lignes contenant uniquement des valeurs manquantes.\n3. Éliminez toutes les lignes contenant au moins une valeur manquante. Combien y a-t-il de lignes de différence ?\n4. Éliminez toutes les colonnes contenant au moins une valeur manquante.\n'

In [88]:
help(df.dropna)

Help on method dropna in module pandas.core.frame:

dropna(*, axis: 'Axis' = 0, how: 'AnyAll | lib.NoDefault' = <no_default>, thresh: 'int | lib.NoDefault' = <no_default>, subset: 'IndexLabel | None' = None, inplace: 'bool' = False, ignore_index: 'bool' = False) -> 'DataFrame | None' method of pandas.core.frame.DataFrame instance
    Remove missing values.

    See the :ref:`User Guide <missing_data>` for more on which values are
    considered missing, and how to work with missing data.

    Parameters
    ----------
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Determine if rows or columns which contain missing values are
        removed.

        * 0, or 'index' : Drop rows which contain missing values.
        * 1, or 'columns' : Drop columns which contain missing value.

        Only a single axis is allowed.

    how : {'any', 'all'}, default 'any'
        Determine if row or column is removed from DataFrame, when we have
        at least one NA or all NA.

       

Question 1 $\\$
L'argument "axis" en utilisant la méthode dropna permet de supprimer une ligne (0) ou une colonne (1) contenant des valeurs manquantes.$\\$
L'argument "how" en utilisant la méthode dropna de choisir si on souhaite supprimer une ligne ou une colonne où toutes les valeurs sont manquantes ( avec all ) ou alors si l'on souhaite supprimer une ligne ou une colonne ou au moins une valeur est manquante (any).
    

Question 2

In [92]:
df_vm_1 = df.dropna(how='all', axis=0)

Question 3

In [93]:
df_vm_2= df.dropna(how='any', axis=0)
difference_lignes_vm = len(df) - len(df_vm_2)
print(f"Nombre de lignes supprimées : {difference_lignes_vm}")

Nombre de lignes supprimées : 119


Question 4

In [94]:
df_vm_colonne = df.dropna(how='any', axis=1)

In [107]:
"""
EXERCICE - La méthode fillna
La méthode dropna permet d'imputer les valeurs manquantes (NaN). Lisez d'abord sa documentation.
1. Quelles sont les différentes stratégies de remplissage des valeurs manquantes ?
2. Imputez les valeurs manquantes de la colonne age du DF donné en exemple par :
    - 0
    - la dernière valeur précédente/suivante valide
    - la moyenne
    - la valeur la plus courante (mode)
3. Quel est le meilleur choix dans ce cas ? Et pour le cas d'une variable temporelle, par exemple la température 'EGT_SEL' de notre jeu de données ?
"""
exemple = pd.DataFrame({'nom': ['Alice', 'Bob', 'Charlie', 'David'], 'age': [24, np.nan, 99, 24]})
print(exemple)



       nom   age
0    Alice  24.0
1      Bob   NaN
2  Charlie  99.0
3    David  24.0


In [98]:
help(df.fillna)

Help on method fillna in module pandas.core.generic:

fillna(value: 'Hashable | Mapping | Series | DataFrame | None' = None, *, method: 'FillnaOptions | None' = None, axis: 'Axis | None' = None, inplace: 'bool_t' = False, limit: 'int | None' = None, downcast: 'dict | None | lib.NoDefault' = <no_default>) -> 'Self | None' method of pandas.core.frame.DataFrame instance
    Fill NA/NaN values using the specified method.

    Parameters
    ----------
    value : scalar, dict, Series, or DataFrame
        Value to use to fill holes (e.g. 0), alternately a
        dict/Series/DataFrame of values specifying which value to use for
        each index (for a Series) or column (for a DataFrame).  Values not
        in the dict/Series/DataFrame will not be filled. This value cannot
        be a list.
    method : {'backfill', 'bfill', 'ffill', None}, default None
        Method to use for filling holes in reindexed Series:

        * ffill: propagate last valid observation forward to next valid.


Question 1 $\\$
Tout d'abord nous pouvons remplir par une valeur constante le 0.$\\$
Ensuite, nous pouvons utiliser $\textbf{ffill}$ qui rempli les valeurs manquantes avec la dernière valeur précédente valide ou encore $\textbf{bfill}$ qui rempli les valeurs manquantes avec la première valeur suivante valide.$\\$
Enfin, on peut utiliser les statistiques comme la moyenne ($\textbf{mean}$) ou la valeur la plus courante ($\textbf{mode}$).

Question 2

In [110]:
# Avec 0
exemple['age_avec_0'] = exemple['age'].fillna(0)
#Avec la dernière valeur précédente/suivante valide
exemple['age_avec_ffill'] = exemple['age'].ffill()
exemple['age_avec_bfill'] = exemple['age'].bfill()

#Avec la moyenne
moyenne_age = exemple['age'].mean()
exemple['age_avec_moyenne'] = exemple['age'].fillna(moyenne_age)

#Avec la valeur la plus courante (mode)
mode_age = exemple['age'].mode()[0]
exemple['age_avec_mode'] = exemple['age'].fillna(mode_age)

print(exemple)

       nom   age  age_avec_0  age_avec_ffill  age_avec_bfill  \
0    Alice  24.0        24.0            24.0            24.0   
1      Bob   NaN         0.0            24.0            99.0   
2  Charlie  99.0        99.0            99.0            99.0   
3    David  24.0        24.0            24.0            24.0   

   age_avec_moyenne  age_avec_mode  
0              24.0           24.0  
1              49.0           24.0  
2              99.0           99.0  
3              24.0           24.0  


Question 3 $\\$
Selon moi, le meilleur choix serait la moyenne ou le mode dans ce cas car cela offre une cohérence des données. $\\$
Pour une variable de température je pense qu'il est préférable d'utiliser bfill ou ffill car on garde une certaine continuité temporelle.

In [114]:
df['EGT_SEL_avec_ffill'] = df['EGT_SEL'].ffill()
df['EGT_SEL_avec_bfill'] = df['EGT_SEL'].bfill()

## Git

Créer un compte GitHub : https://github.com/

Créer un nouveau repository :
1. Sélectionner "Nouveau dépôt" dans le menu déroulant avec le signe +. 
2. Saisisser un nom pour votre dépôt (par exemple, "TDs statistiques descriptives") 
3. Cliquer sur "Créer un dépôt". Ne vous souciez pas des autres options.



Télécharger Git Bash : https://git-scm.com/downloads

Sur Git Bash, positionnez-vous dans le répertoire où votre projet figure.

Ensuite

> git init

> git remote add origin https://github.com/********

> git add .

> git commit -m "Ajout du TD1"

> git push origin master

C'est tout ! Vous avez créé votre repo GitHub ! 